version: '3'

services:
  db:
    image: postgres:14
    environment:
      POSTGRES_DB: jinjadx
      POSTGRES_USER: jinjadx
      POSTGRES_PASSWORD: jinjadx_password
      POSTGRES_HOST_AUTH_METHOD: scram-sha-256
    ports:
      - "5434:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U jinjadx"]
      interval: 5s
      timeout: 5s
      retries: 5

  backend:
    build: ./backend
    volumes:
      - ./backend:/app
    ports:
      - "8000:8000"
    depends_on:
      db:
        condition: service_healthy
    environment:
      - PYTHONUNBUFFERED=1
    command: >
      sh -c "
        echo 'Checking libpq version:' &&
        dpkg -s libpq-dev | grep Version &&
        python manage.py migrate &&
        python manage.py runserver 0.0.0.0:8000
      "

  frontend:
    build: ./frontend
    volumes:
      - ./frontend:/app
    ports:
      - "3000:3000"
    depends_on:
      - backend
